### PR TITLE
Reset dummy-file

### PR DESCRIPTION
**Pull request by mrhillsman**

### CODE REVIEW

**Comment by mrhillsman** [comment]
recheck

**Comment by codebauss** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/116b180ead054424ae13998138932b7e : POST_FAILURE in 1m 21s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible wordpress-ansible : NODE_FAILURE

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- wordpress-ansible http://80.158.20.68/logs/14/14/72087dfcc6ce30a7c87fbf8da1965faa2c684529/check/wordpress-ansible/d25bd8f/ : SUCCESS in 2m 25s

**Pull request closed without merging**
