### PR TITLE
call zuul 0

### PR DESCRIPTION
**Pull request by mrhillsman**

### CODE REVIEW

**Comment by mrhillsman** [comment]
Build failed.

- noop noop : SUCCESS in 0s
- simple finger://openlab-cicd-zuul/50cfaf4261e34394aa68be6693834e5b : SUCCESS in 38s
- wordpress-ansible finger://openlab-cicd-zuul/2d1fcc17911d48ba872cadbb36dac1ea : FAILURE in 7s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- simple simple : MERGER_FAILURE
- wordpress-ansible wordpress-ansible : MERGER_FAILURE

**Comment by codebauss** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- simple simple : MERGER_FAILURE
- wordpress-ansible wordpress-ansible : MERGER_FAILURE

**Comment by codebauss** [comment]
recheck

**Comment by codebauss** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- simple finger://openlab-cicd-zuul/3716f9553d5a4fddb5e5c2fa2cd20a6c : SUCCESS in 38s
- wordpress-ansible finger://openlab-cicd-zuul/3a5eb90f705e4f25a8d4208cd80e7e2c : FAILURE in 7s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- simple finger://openlab-cicd-zuul/e2bb6df4d7df40ec8e7e2954c08a2251 : SUCCESS in 38s
- wordpress-ansible finger://openlab-cicd-zuul/72bf2584c0ba4a479145fbb49e944f33 : FAILURE in 14s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- simple finger://openlab-cicd-zuul/380339fd2adf4d00a0fb61127ad48f57 : SUCCESS in 38s
- wordpress-ansible finger://openlab-cicd-zuul/a003c6e22a4146269be9dbf96147b203 : FAILURE in 14s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/3d62c46d0ebe423e9491f8b884502536 : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/ead9510f358c4597aa9d9c9188140da9 : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/64b654a2c9d343f796fdb53a54c3b06b : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/a07c1fc68f414cbb88b77c568039872e : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/7964dfe2e1184ffd8b41c5efda7c9e95 : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/967d895fd4204c2e8ace7f21413048e5 : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/7443e737c9204dfbaa7a7313f5d22595 : FAILURE in 1m 04s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/0b97cfd8c0a146e8ae8a16773a5e5479 : FAILURE in 1m 10s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible wordpress-ansible : NODE_FAILURE

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/acc2f7cde43b4599990a532408f471e7 : FAILURE in 1m 04s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/b5b81bf5845842339e6abeb22b108096 : FAILURE in 8s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- wordpress-ansible finger://openlab-cicd-zuul/b7620b4bc2da4d18873e530066fa939d : SUCCESS in 1m 38s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- wordpress-ansible finger://openlab-cicd-zuul/fa925dbd99c64da0b7106abd1ee8ced2 : SUCCESS in 1m 12s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- wordpress-ansible finger://openlab-cicd-zuul/3432c2dff11143969b274d340d33b543 : SUCCESS in 1m 18s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/d190f9fb83b74cfbbf106af499690f44 : SUCCESS in 1m 21s
- isstreamworking finger://openlab-cicd-zuul/73e86f43012b43638b7f9547681c8ff3 : TIMED_OUT in 30m 16s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/ad82af933b6f465e98280263d647e173 : SUCCESS in 1m 22s
- isstreamworking finger://openlab-cicd-zuul/fa3627d3f0044ed3b3de8b79b8fca992 : TIMED_OUT in 30m 15s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/1b9df07b8dbb46ca8414424c351fe666 : SUCCESS in 1m 16s
- isstreamworking finger://openlab-cicd-zuul/3a39f9312bf64a5a8499fe199e5d9967 : TIMED_OUT in 30m 16s

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- wordpress-ansible finger://openlab-cicd-zuul/68fb042baaa34d6d857a6129f6d5f305 : FAILURE in 14s
- isstreamworking finger://openlab-cicd-zuul/07054e774d4b4d45956318bdfc772670 : TIMED_OUT in 30m 15s

**Comment by mrhillsman** [comment]
recheck

**Pull request closed without merging**
